# ----------------- DATA CONFIG ------------------- #
# interval: 1m | 3m | 5m | 15m | 30m | 1h | 2h | 4h | 6h | 8h | 12h | 1d | 3d | 1w | 1M
interval: 1h

# futures | spot
market: futures

# Use limit type 'datetime' if you want to limit the number of records by a given date
# or use limit type 'max_records' to limit the number of maximum records
# or use ignore to keep all records (ignores the limit value).
limit:
  # type: datetime | max_records | ignore
  type: ignore
  # value:
  # max_records: 5000, 10000, ...
  # date_time: 2021-01-01 00:00:00 (ISO 8601 format), 1609455600 (timestamp in seconds)
  value: 5000

# Define which columns you would like to include:
# open_time, open_price, high_price, low_price, close_price,
# volume, close_time, quote_asset_volume, number_of_trades,
# taker_buy_base_asset_volume, taker_buy_quote_asset_volume
columns: [open_time, open_price, high_price, low_price, close_price, volume, number_of_trades]

symbols: [btcusdt]

database_path: data/binance_candles.db


# ------------- TRADING BOT CONFIG --------------- #

# mode: backtest | binance
mode: backtest

trader:
  # 'ratio': > 0 and < 1
  # Note: Avoid values close to 0 and 1.
  ratio: 0.9

strategy:
  # A class which is implemented in the strategy module
  type: RSIStrategy
  # Define one or more symbols to trade.
  # 1. If strategy works with multiple symbols:
  #    symbols: [btcusdt, ethusdt, ..., xrpusdt]
  # 2. If it works with only one symbol:
  #    symbol: btcusdt
  symbol: btcusdt

indicators:
  rsi:
    type: RSIIndicator
    column: close_price
    time_period: 14
    upper_limit: 70.0
    lower_limit: 30.0
