from crypto_data.binance.schema import (
    OPEN_TIME,
    OPEN_PRICE,
    HIGH_PRICE,
    LOW_PRICE,
    CLOSE_PRICE,
    VOLUME,
)

OPEN_TIME_INDEX = 0
OPEN_PRICE_INDEX = 1
HIGH_PRICE_INDEX = 2
LOW_PRICE_INDEX = 3
CLOSE_PRICE_INDEX = 4
VOLUME_INDEX = 5

COLUMN_NAME_INDEX_MAP = {
    OPEN_TIME: OPEN_TIME_INDEX,
    OPEN_PRICE: OPEN_PRICE_INDEX,
    HIGH_PRICE: HIGH_PRICE_INDEX,
    LOW_PRICE: LOW_PRICE_INDEX,
    CLOSE_PRICE: CLOSE_PRICE_INDEX,
    VOLUME: VOLUME_INDEX,
}
